// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ntgraphctrl3.h"

/////////////////////////////////////////////////////////////////////////////
// CNtgraphctrl3

IMPLEMENT_DYNCREATE(CNtgraphctrl3, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNtgraphctrl3 properties

/////////////////////////////////////////////////////////////////////////////
// CNtgraphctrl3 operations
